//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentanaFinal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Card_WordingTemplates = new HashSet<Card_WordingTemplates>();
        }
    
        public int id_card { get; set; }
        public string CardName { get; set; }
        public string FeaturedImage { get; set; }
        public string FrontImage { get; set; }
        public string BackImage { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<Card_WordingTemplates> Card_WordingTemplates { get; set; }
    }
}
