//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentanaFinal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_WordingTemplates_TemplateFields
    {
        public int id_wording_template_field { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string DefaultValue { get; set; }
        public decimal xPos { get; set; }
        public decimal yPos { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public int fk_wording_template { get; set; }
    
        public virtual Card_WordingTemplates Card_WordingTemplates { get; set; }
    }
}
