//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentanaFinal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int id_company { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
