//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentanaFinal.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentanaEntities : DbContext
    {
        public VentanaEntities()
            : base("name=VentanaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<Card_WordingTemplates> Card_WordingTemplates { get; set; }
        public DbSet<Card_WordingTemplates_TemplateFields> Card_WordingTemplates_TemplateFields { get; set; }
        public DbSet<Card> Cards { get; set; }
        public DbSet<Company> Companies { get; set; }
    }
}
